// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

// use chrono::DateTime;
// use chrono::offset::Utc;
use diesel::Queryable;
use serde::Serialize;

#[derive(Queryable, Debug, Serialize)]
pub struct Conductora {
    pub id: i32,
    pub nombre: String,
    pub edad: Option<i32>,
    pub telefono: String,
    pub correo: String,
    pub area: String,
}

